In [28]:
import numpy as np 
import pandas as pd


In [29]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [30]:
df = pd.read_csv('covid_toy.csv')
df.head()
# gender, city = nominal categorical data
# fever = simple imputer
# cough = ordinal encoder

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [31]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [32]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('has_covid', axis = 1)
                                                 ,df['has_covid'],test_size = 0.2)
x_train

,age,gender,fever,cough,city
63,10,Male,100.0,Mild,Bangalore
32,34,Female,101.0,Strong,Delhi
78,11,Male,100.0,Mild,Bangalore
95,12,Female,104.0,Mild,Bangalore
53,83,Male,98.0,Mild,Delhi
...,...,...,...,...,...
62,56,Female,104.0,Strong,Bangalore
98,5,Female,98.0,Strong,Mumbai
76,80,Male,100.0,Mild,Bangalore
40,49,Female,102.0,Mild,Delhi


## Long process doing operations one by one

In [33]:
# adding simple imputer to fever col
si = SimpleImputer()
# all values of fever filled with the mean value
x_train_fever = si.fit_transform(x_train[['fever']])
# also the test data
x_test_fever = si.fit_transform(x_test[['fever']])
x_train_fever

array([[100.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [103.        ],
       [100.86111111],
       [102.        ],
       [104.        ],
       [104.        ],
       [100.86111111],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [100.86111111],
       [101.        ],
       [103.        ],
       [102.        ],
       [101.        ],
       [100.86111111],
       [102.        ],
       [101.        ],
       [ 99.        ],
       [100.86111111],
       [101.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [103.        ],
       [104.        ],
       [ 98

In [34]:
# ordinal encoder cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])
x_train_cough

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],

In [41]:
ohe = OneHotEncoder(drop = 'first', sparse_output = False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])
x_train_gender_city

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],


In [45]:
ohe.get_feature_names_out(['gender', 'city'])

array(['gender_Male', 'city_Delhi', 'city_Kolkata', 'city_Mumbai'],
      dtype=object)

In [37]:
# x_train_age = df.drop(df[['gender','fever','cough','city','has_covid']], axis = 1)
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values
x_train_age

array([[10],
       [34],
       [11],
       [12],
       [83],
       [68],
       [47],
       [51],
       [71],
       [46],
       [42],
       [24],
       [34],
       [25],
       [38],
       [19],
       [81],
       [27],
       [65],
       [55],
       [83],
       [22],
       [74],
       [42],
       [15],
       [50],
       [23],
       [81],
       [60],
       [82],
       [51],
       [71],
       [69],
       [64],
       [65],
       [75],
       [19],
       [73],
       [25],
       [51],
       [ 6],
       [83],
       [16],
       [10],
       [31],
       [20],
       [49],
       [64],
       [34],
       [40],
       [19],
       [26],
       [24],
       [34],
       [59],
       [49],
       [20],
       [20],
       [ 8],
       [12],
       [65],
       [44],
       [54],
       [75],
       [72],
       [60],
       [65],
       [84],
       [69],
       [ 5],
       [47],
       [27],
       [17],
       [82],
       [69],
       [56],
       [ 5],

In [43]:
print(x_train_age.shape)
print(x_train_fever.shape)
print(x_train_gender_city.shape)
print(x_train_cough.shape)

(80, 1)
(80, 1)
(80, 4)
(80, 1)


In [44]:
x_train_transform = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis = 1)
x_test_transfrom = np.concatenate((x_test_age, x_test_fever,x_test_gender_city,x_test_cough),axis = 1)
x_train_transform

array([[ 10.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 11.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 12.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 83.        ,  98.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 68.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 47.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.    

# Column Transformer
## Transforming all the columns all at once 

In [46]:
from sklearn.compose import ColumnTransformer

In [54]:
# object      = operation        (list of all operations, rest remaining)
# transformer = ColumnTransformer(transformers=[],remainder = 'passthrough')
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop = 'first'),['gender','city'])
],remainder = 'passthrough')
#remainder [passthrough = dont tough just pass, drop = remove]

In [51]:
transformer.fit_transform(x_train).shape

(80, 7)

In [52]:
transformer.fit_transform(x_test).shape

(20, 7)

In [55]:
transformer.fit_transform(x_test)

array([[ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  13.        ],
       [103.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  73.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  23.        ],
       [ 98.        ,   0.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  80.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.    